<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\GBFR.ExtraSigilSlots.Reloaded\VirtualSlotCountInput.cs"
             Link="VirtualSlotCountInput.cs" />
  </ItemGroup>
</Project>
