package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// MaxSlots mirrors the managed editor limit (must stay in sync).
const MaxSlots = 12

// LoadoutService reads the mod-directory data files (sigils.json,
// character-exclusives.json, tool-hotkey.txt — all next to the exe) and
// writes the player configuration (LOCALAPPDATA/GBFRPreEquippedSigils,
// mirroring the mod's userCfgDir so mod updates never wipe it).
// Protocol is shared with the mod: sigils.json (merged sigil/trait table:
// item rows hash != skill1, non-item skill rows hash == skill1) and
// loadout.json (player configuration; array format: [ { items: [{hash,level,zh,en},
// {hash,level,zh,en}?], enabled } ]).
type LoadoutService struct{}

// MinimiseApp hides the window to the tray; the process stays alive so the
// in-game hotkey can bring the window back instantly. Invoked by the shared
// hotkey inside the tool (the X button is handled by the WndProc interceptor
// in main.go and hides the window directly).
func (s *LoadoutService) MinimiseApp() {
	if win != nil {
		win.Hide()
	}
}

// GetHotkey returns the configured menu hotkey as a virtual key code.
// The mod publishes it in tool-hotkey.txt (mod directory, next to the exe);
// missing file falls back to F1 (0x70).
func (s *LoadoutService) GetHotkey() (int, error) {
	data, err := os.ReadFile(filepath.Join(exeDir(), "tool-hotkey.txt"))
	if err != nil {
		return 0x70, nil
	}
	if vk, err := strconv.Atoi(strings.TrimSpace(string(data))); err == nil && vk > 0 {
		return vk, nil
	}
	return 0x70, nil
}

type loadoutItem struct {
	Gem   string `json:"gem"`  // items[0]: gem (物品) hash
	Hash  string `json:"hash"` // items[1]: trait (词条) hash
	Level int    `json:"level"`
	Zh    string `json:"zh"`
	En    string `json:"en"`
}

type loadoutSlot struct {
	Items   []loadoutItem `json:"items"`
	Enabled bool          `json:"enabled"`
}

// exclusiveState mirrors the mod-side "exclusive" section: keyed by player
// code (or name/hash), inner keys are the factor trait hashes, true = enabled
// (default when omitted). Parsed only to validate the config; the payload is
// written verbatim.
type exclusiveState map[string]bool

func exeDir() string {
	exe, err := os.Executable()
	if err != nil {
		return "."
	}
	return filepath.Dir(exe)
}

// userCfgDir is where the player configuration (loadout.json) lives. The mod
// folder is replaced on every update; this location survives them. Must match
// the C# side (Environment.SpecialFolder.LocalApplicationData): do NOT fall
// back to os.UserConfigDir() here — on Windows that returns %AppData%
// (Roaming), which would diverge from the mod's LocalAppData path.
func userCfgDir() string {
	base := os.Getenv("LOCALAPPDATA")
	if base == "" {
		base = exeDir()
	}
	return filepath.Join(base, "GBFRPreEquippedSigils")
}

// readModData reads one of the mod-directory data files (the mod folder is
// replaced on every update; the files ship with the release).
func readModData(name string) (string, error) {
	data, err := os.ReadFile(filepath.Join(exeDir(), name))
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// LoadSigils returns the merged sigil/trait table (sigils.json): item rows
// plus non-item skill rows (hash == skill1). All pickers read from it.
func (s *LoadoutService) LoadSigils() (string, error) {
	return readModData("sigils.json")
}

// LoadConfig returns the player configuration from the user directory; an
// empty config is returned when none exists yet (the editor starts from
// zero - there is no built-in preset anymore).
func (s *LoadoutService) LoadConfig() (string, error) {
	data, err := os.ReadFile(filepath.Join(userCfgDir(), "loadout.json"))
	if err != nil {
		if os.IsNotExist(err) {
			return `{"lang":"zh","slots":[]}`, nil
		}
		return "", err
	}
	return string(data), nil
}

// LoadExclusives returns the per-character exclusive-factor table
// (character-exclusives.json, generated by docs/tool-gen-loadout.ps1).
func (s *LoadoutService) LoadExclusives() (string, error) {
	return readModData("character-exclusives.json")
}

// validateSlots enforces the shared schema limits.
func validateSlots(slots []loadoutSlot) error {
	if len(slots) > MaxSlots {
		return fmt.Errorf("too many slots: %d (max %d)", len(slots), MaxSlots)
	}
	for i, slot := range slots {
		if len(slot.Items) < 1 || len(slot.Items) > 2 {
			return fmt.Errorf("slot %d: items must have 1 or 2 entries", i+1)
		}
		if slot.Items[0].Gem == "" {
			return fmt.Errorf("slot %d: item gem is empty", i+1)
		}
		if len(slot.Items) == 2 && slot.Items[1].Hash == "" {
			return fmt.Errorf("slot %d: second item hash is empty", i+1)
		}
		for _, item := range slot.Items {
			if item.Level < 0 || item.Level > 200 {
				return fmt.Errorf("slot %d: level out of range", i+1)
			}
		}
	}
	return nil
}

// SaveLoadout writes the player configuration (same schema as the mod reads:
// {lang, slots:[{items:[...],enabled}]}; a bare array is accepted too for
// backwards compatibility). Atomic write (temp + rename) so the mod's 250ms
// mtime tick never sees a half-written file.
func (s *LoadoutService) SaveLoadout(config string) error {
	var c struct {
		Lang      string                    `json:"lang"`
		Slots     []loadoutSlot             `json:"slots"`
		Exclusive map[string]exclusiveState `json:"exclusive"`
	}
	if err := json.Unmarshal([]byte(config), &c); err != nil {
		return err
	}
	slots := c.Slots
	if slots == nil {
		// legacy bare-array config
		var arr []loadoutSlot
		if err := json.Unmarshal([]byte(config), &arr); err != nil {
			return err
		}
		slots = arr
	}
	if err := validateSlots(slots); err != nil {
		return err
	}
	dir := userCfgDir()
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	path := filepath.Join(dir, "loadout.json")
	// Unique temp name (the frontend debounce can fire two saves in flight):
	// concurrent writers never share one tmp file, so a half-written file can
	// never be renamed into place.
	tmp, err := os.CreateTemp(dir, "loadout.json.*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	if _, err := tmp.WriteString(config); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return err
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return err
	}
	return os.Rename(tmpName, path)
}
