export const MAX_SLOTS = 12 // fixed rows shown in the editor

export interface Slot {
  mainHash: string
  mainLevel: number
  secHash: string
  secLevel: number
  enabled: boolean
}

export interface Sigil {
  hash: string // gem hash (= item identity; skill entries use the trait hash)
  name: string // display name (base, level suffix stripped); grouping key
  zh: string
  skill1: string // primary trait hash
  category: string
  player: string
  special: boolean
  cap?: number // trait level cap (row data, feeds the trait dictionary only)
  lot?: string[] // pool versions: legal secondary trait hashes (empty = no pool)
  sec?: string // fixed-second versions: the fixed secondary trait hash
}

export interface Trait {
  hash: string
  zh: string
  en: string
  cap: number
  nonItem: boolean // non-item skill row (hash == skill1): cannot combine as secondary
}

/** One row of character-exclusives.json (generated by tool-gen-loadout.ps1). */
export interface Exclusive {
  hash: string
  player: string
  name?: string
  zh?: string
  t1: string
  t2: string
  war: string
  t1Gem: string
  t2Gem: string
  warGem: string
}

/** Exclusive overlay written to loadout.json: player code -> trait hash -> enabled. */
export type ExclusiveState = Record<string, Record<string, boolean>>

export const emptySlot = (): Slot => ({ mainHash: "", mainLevel: 0, secHash: "", secLevel: 0, enabled: true })

/** Normalize a saved config (new array format) into Slot[] (mainHash = name).
 * Stored gems are mapped to display names via the sigil table; unknown gems
 * keep their raw value. */
export function configToSlots(parsed: { slots?: unknown }, sigils: Sigil[]): Slot[] {
  const fromCfg = slotsFromConfig(parsed?.slots)
  const nameOfHash = new Map(sigils.map((s) => [s.hash, s.name]))
  for (const s of fromCfg) {
    if (nameOfHash.has(s.mainHash)) s.mainHash = nameOfHash.get(s.mainHash) as string
  }
  return fromCfg
}

/** Pad the editor to at least MAX_SLOTS rows so the user just fills them in.
 * Extra rows from an over-long saved config pass through: the Go/C# validators
 * reject them instead of silently truncating (data loss on next autosave). */
export function pad12(slots: Slot[]): Slot[] {
  const out = [...slots]
  while (out.length < MAX_SLOTS) out.push(emptySlot())
  return out
}

/** Normalize a saved config (new array format) into Slot[] (mainHash = name). */
export function slotsFromConfig(raw: unknown): Slot[] {
  const arr = Array.isArray(raw) ? raw : []
  return arr.map((slot) => {
    const s = (slot ?? {}) as {
      enabled?: boolean
      items?: { gem?: string; hash?: string; level?: number }[]
    }
    const items = Array.isArray(s.items) ? s.items : []
    const main = items[0] ?? {}
    const sec = items[1]
    return {
      mainHash: typeof main.gem === "string" ? main.gem : "", // items[0] has no "hash" variant (never written)
      mainLevel: typeof main.level === "number" ? main.level : 15,
      secHash: sec && typeof sec.hash === "string" ? sec.hash : "",
      secLevel: sec && typeof sec.level === "number" ? sec.level : 15,
      enabled: s.enabled !== false,
    }
  })
}
